bind-key -r h select-pane -L
bind-key -r l select-pane -R 
bind-key -r k select-pane -U 
bind-key -r j select-pane -D  
bind-key v swap-pane -s '!'

unbind %
unbind '"'
unbind M-4 
unbind M-3 

bind-key \\ split-window -h
bind-key - split-window -v
bind-key | select-layout main-vertical
bind-key _ select-layout main-horizontal
set-window-option -g mode-keys vi

